### ISSUE TITLE
Pius crashes when signing key containing not only email addresses

### ISSUE THREAD

**Issue by wget** [jaymzh/pius#11]
Since my rolling release Arch Linux distribution does not use GnuPG branch 1.x for ages, I was using the branch https://github.com/miquelruiz/pius/tree/gpg-2.1.4 from @miquelruiz. I was trying to sign some keys which do not only contain email addresses, like for example embedded picture, etc. When I try to do so, pius crashes with these kind of keys.

```
python2 ./pius -dv --mail-host=smtp.gmail.com --no-pgp-mime --mail=user@mail.com --signer=0E7DE52C04D71683 -u user@mail.com -r ~/.gnupg/pubring.kbx -n user@mail.com 15F51B3090884649          Welcome to PIUS, the PGP Individual UID Signer.

Setting debug
NOTE: -O and -m are present, turning on -e
NOTE: See the README about security implications.
Please enter your PGP passphrase: 
DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-armor', '--always-trust', '-r', '0E7DE52C04D71683', '-e', '/tmp/pius_tmp/pius_tmp']
DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--command-fd', '0', '--passphrase-fd', '0', '--status-fd', '1', '--output', '/tmp/pius_tmp/pius_tmp2', '-d', '/tmp/pius_tmp/pius_tmp.gpg']
DEBUG: Sending passphrase
DEBUG: wait()ing on gpg
Please enter your mail server password: 
DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-default-keyring', '--keyring', '/somePath/.gnupg/pubring.kbx', '--fingerprint', '15F51B3090884649']
pub   rsa4096/15F51B3090884649 2014-11-13
      Key fingerprint = B36E AA8C 4EAF DB59 FAA0  1771 15F5 1B30 9088 4649
uid                 [  undef ] Peter A. Now�e
uid                 [ unknown] Peter Nowee <XXX@YYY.com>
uid                 [ unknown] Peter Nowee <XXX@YYY.com>
uid                 [ unknown] Peter Nowee <XXX@YYY.com>
uid                 [  undef ] [jpeg image of size 8773]
sub   rsa4096/DF9C27A3AEC052B9 2014-11-13 [expires: 2016-11-12]
sub   rsa4096/DB4E8AD69A0414CD 2014-11-13 [expires: 2016-11-12]

Have you verified this user/key, and if so, what level do you want to sign at?
  0-3, Show again, Next, Help, or Quit? [0|1|2|3|s|n|h|q] (default: n) 3

Signing all UIDs on key 15F51B3090884649
DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--command-fd', '0', '--passphrase-fd', '0', '--status-fd', '1', '--no-default-keyring', '--keyring', '/somePath/.gnupg/pubring.kbx', '--no-options', '--with-colons', '--edit-key', '15F51B3090884649']
DEBUG: Got a line pub:q:4096:1:15F51B3090884649:1415885910:0::-:::sc
DEBUG: Got a line fpr:::::::::B36EAA8C4EAFDB59FAA0177115F51B3090884649:
DEBUG: Got a line sub:q:4096:1:DF9C27A3AEC052B9:1415885910:1478960670:::::e
DEBUG: Got a line fpr:::::::::F54A342190918182401193B8DF9C27A3AEC052B9:
DEBUG: Got a line sub:q:4096:1:DB4E8AD69A0414CD:1415886921:1478958921:::::s
DEBUG: Got a line fpr:::::::::3F8F5CC515992FAAD210C5A6DB4E8AD69A0414CD:
DEBUG: Got a line uid:q::::::::Peter A. Nowée:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:1,p:
DEBUG: Got UID Peter A. Nowée with status q
DEBUG: no email
DEBUG: 15F51B3090884649__Peter_A._Nowée__0E7DE52C04D71683 isn't in []
DEBUG: Got a line uid:-::::::::Peter Nowee <XXX@YYY.com>:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:2,:
DEBUG: Got UID Peter Nowee <XXX@YYY.com> with status -
DEBUG: got email XXX@YYY.com
DEBUG: 15F51B3090884649__peter.nowee_at_gmail.com__0E7DE52C04D71683 isn't in ['15F51B3090884649__Peter_A._Now\xc3\xa9e__0E7DE52C04D71683']
DEBUG: Got a line uid:-::::::::Peter Nowee <XXX@YYY.com>:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:3,:
DEBUG: Got UID Peter Nowee <XXX@YYY.com> with status -
DEBUG: got email XXX@YYY.com
DEBUG: 15F51B3090884649__XXX_at_YYY.com__0E7DE52C04D71683 isn't in ['15F51B3090884649__Peter_A._Now\xc3\xa9e__0E7DE52C04D71683', '15F51B3090884649__XXX_at_YYY.com__0E7DE52C04D71683']
DEBUG: Got a line uid:-::::::::Peter Nowee <XXX@YYY.com>:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:4,:
DEBUG: Got UID Peter Nowee <XXX@YYY.com> with status -
DEBUG: got email XXX@YYY.com
DEBUG: 15F51B3090884649__peter.nowee_at_aiba.nl__0E7DE52C04D71683 isn't in ['15F51B3090884649__Peter_A._Now\xc3\xa9e__0E7DE52C04D71683', '15F51B3090884649__XXX_at_YYY.com__0E7DE52C04D71683', '15F51B3090884649__XXX_at_YYY.com__0E7DE52C04D71683']
DEBUG: Got a line uat:q::::::::1 8795:::S9 S8 S7 S3 H10 H9 H8 H11 Z2 Z3 Z1 Z0,mdc,no-ks-modify:5,:
DEBUG: got to command prompt
DEBUG: quitting
DEBUG: waiting
  There are 4 UIDs on this key to sign
DEBUG: exporting 15F51B3090884649
DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-default-keyring', '--keyring', '/somePath/.gnupg/pubring.kbx', '--armor', '--output', '/tmp/pius_tmp/15F51B3090884649.asc', '--export', '15F51B3090884649', '0E7DE52C04D71683']
  UID 1 (Peter_A._Nowée): DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--no-default-keyring', '--keyring', '/tmp/pius_tmp/pius_keyring.gpg', '--import-options', 'import-minimal', '--import', '/tmp/pius_tmp/15F51B3090884649.asc']
DEBUG: ['/usr/bin/gpg', '--keyid-format', 'long', '-q', '--no-tty', '--no-auto-check-trustdb', '--batch', '--command-fd', '0', '--passphrase-fd', '0', '--status-fd', '1', '--no-default-keyring', '--keyring', '/tmp/pius_tmp/pius_keyring.gpg', '-u', '0E7DE52C04D71683', '--default-cert-level', '3', '--no-ask-cert-level', '--edit-key', '15F51B3090884649']
DEBUG: Sending passphrase
DEBUG: Waiting for prompt
DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: Selecting UID 1
DEBUG: Waiting for ack
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Running sign subcommand
DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: Sending sign command
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Waiting for response
DEBUG: Got [GNUPG:] GET_BOOL sign_uid.okay

DEBUG: Confirming signing
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Got [GNUPG:] GET_LINE keyedit.prompt

  ERROR: GPG didn't sign.
Traceback (most recent call last):
  File "./pius", line 395, in <module>
    main()
  File "./pius", line 379, in main
    if signer.sign_all_uids(key, retval):
  File "/home/wget/Downloads/pius-fb/libpius/signer.py", line 676, in sign_all_uids
    res = self.sign_uid(key, uid['index'], level)
  File "/home/wget/Downloads/pius-fb/libpius/signer.py", line 629, in sign_uid
    raise GpgUnknownError(line)
libpius.exceptions.GpgUnknownError: [GNUPG:] GET_LINE keyedit.prompt

```

The normal behavior would be to sign the embedded part and send that part to all email addresses present in the key. I don't know what your script actually does. After reading the code (even if I'm far from being fluent in Python), I don't see a location where all non email addresses items are signed, encrypted and sent to all mail items from the key.

This is happening when I try to sign the key from Peter A Nowée, 15F51B3090884649 which contain that kind of picture.

Help would be greatly appreciated.

**Comment by jaymzh** [comment]
What version of gpg are you using? We skip image UIDs very specifically - this crash looks like what you get when you are using gpg2 which we don't yet support.

**Comment by wget** [comment]
Yes this is gpg2. I know you are not supporting it yet (see a previous issue I reported), but I was using a forked branch from @miquelruiz, and seemingly, all was not implemented yet to support GPG 2.

Btw @jaymzh, how should pius react when using gpg 1 with image UIDs? Do you sign them and send them to each UID address?

Also, does pius react when we need so sign all UIDs addresses? Does pius remove uids from keys? You send only the uid that was signed to each email address, removing other UIDs from the key. Or does Pius send all uids, but only one uid will have the new signature, leaving the key untouched (do not remove other UIDs)?

**Comment by jaymzh** [comment]
Currently pius will skip image UIDs (and state that it is doing so) because we have no way of letting the user verify them. I plan to use `display` in a future version to allow this.

And we send a full key, but have only signed the relevant UID.

**Comment by wget** [comment]
Ok. Thanks for the clarification.

It's a pity pius does not have this feature. gcaff, a GUI for caff, has this feature included. And at FOSDEM I have been asked to sign some image UID, some participants like Peter Nowee gave to me a picture of the UID image enclosed in his key. Gonna have to find a workaround to sign them.

Also, as a developer, I would like to know how are you actually determining gpg is returning lines like `GET_LINE keyedit.prompt`, `BEGIN_ENCRYPTION`, etc. (see. lines 20 to 35 in `signer.py` for example)?  Since these lines only appear when we specify `-q --not--ty, --batch`, how are you doing to determine them (stdout redirection?)?

**Comment by jaymzh** [comment]
Lines 46-68:
```
    self.gpg_fd_opts = [
          '--command-fd', '0',
          '--passphrase-fd', '0',
          '--status-fd', '1',
    ]
```
That puts different things on different file descriptors.

**Comment by jaymzh** [comment]
Please file a separate bug for picture UID support.

**Comment by jaymzh** [comment]
Closing this - the actual bug reported here is lack of gpg2 support which is being tracked in #10.

Please file a separate bug for graphical UID support if you'd like it.
