### ISSUE TITLE
Pius crashes when signing

### ISSUE THREAD

**Issue by zorun** [jaymzh/pius#21]
Using the latest version of pius, 2.2.1, with gnupg 2.1.9 on Archlinux, pius can crash in two different ways when signing:

<pre>
File "/usr/bin/pius", line 333, in <module>
main()
File "/usr/bin/pius", line 317, in main
if signer.sign_all_uids(key, retval):
File "/usr/lib/python2.7/site-packages/libpius/signer.py", line 781, in sign_all_uids
self.mailer.send_sig_mail(self.signer, key, uid, self)
File "/usr/lib/python2.7/site-packages/libpius/mailer.py", line 225, in send_sig_mail
signer, uid_data['email'], keyid, uid_data['file'], psign
File "/usr/lib/python2.7/site-packages/libpius/mailer.py", line 175, in _generate_pgp_mime_email
psigner.encrypt_and_sign_file(tmpfile, signed_tmpfile, keyid)
File "/usr/lib/python2.7/site-packages/libpius/signer.py", line 876, in encrypt_and_sign_file
raise EncryptionUnknownError(line)
libpius.exceptions.EncryptionUnknownError: [GNUPG:] PINENTRY_LAUNCHED 10282
</pre>

<pre>
Traceback (most recent call last):
  File "/usr/bin/pius", line 333, in <module>
    main()
  File "/usr/bin/pius", line 317, in main
    if signer.sign_all_uids(key, retval):
  File "/usr/lib/python2.7/site-packages/libpius/signer.py", line 781, in sign_all_uids
    self.mailer.send_sig_mail(self.signer, key, uid, self)
  File "/usr/lib/python2.7/site-packages/libpius/mailer.py", line 225, in send_sig_mail
    signer, uid_data['email'], keyid, uid_data['file'], psign
  File "/usr/lib/python2.7/site-packages/libpius/mailer.py", line 175, in _generate_pgp_mime_email
    psigner.encrypt_and_sign_file(tmpfile, signed_tmpfile, keyid)
  File "/usr/lib/python2.7/site-packages/libpius/signer.py", line 876, in encrypt_and_sign_file
    raise EncryptionUnknownError(line)
libpius.exceptions.EncryptionUnknownError: [GNUPG:] PROGRESS need_entropy X 8 16
</pre>

It seems it has already been fixed in 79d096eea73b40ae97f91140bb2282eebfcf0d2f and 325b1fbb76bb45e852f6ef86feb52a79c2ff702f.  Is it possible to release a new version with these changes?

Thanks!

**Comment by jaymzh** [comment]
Yeah I'll try to get a release out next week.

**Comment by zorun** [comment]
Hi, is there a planned date for the next minor release, with these fixes?

Thanks!

**Comment by jaymzh** [comment]
Sorry - holidays got to me, I'll try to do this soon.

**Comment by jaymzh** [comment]
2.2.2 is now out which fixes this.

**Comment by zorun** [comment]
Thanks!
