### ISSUE TITLE
entropy issue unable to sign any key (tested with latest git too)

### ISSUE THREAD

**Issue by wget** [jaymzh/pius#22]
Hi. I'm still on my way to sign my FOSDEM 2015 keys, nearly one year after the event... Support for gpg2 has arrived in pius, but I am far from being able to sign all of these keys. There is currently no tool which could allow me to do that without an issue. `pius`, `caff`, `gcaff` all have an issue at some steps.

```
Setting debug
NOTE: -O and -m are present, turning on -e
NOTE: -u is present, turning off -S.
DEBUG: Running: /usr/bin/gpg2 --version
Please enter your mail server password: 
DEBUG: Running: /usr/bin/gpg2 --keyid-format long --no-auto-check-trustdb -q --no-tty --batch --no-default-keyring --keyring /home/wget/.gnupg/pubring.kbx --fingerprint 24735DD835689C84
pub   rsa4096/24735DD835689C84 2014-06-07 [expires: 2019-06-06]
      Key fingerprint = 47B2 2252 BF69 14DF 964B  B50C 2473 5DD8 3568 9C84
uid                 [ unknown] Carl Olof Erlandsson <calle@thoughtbot.com>
uid                 [ unknown] Carl Olof Erlandsson <calle@calleerlandsson.com>
sub   rsa4096/ECE04E5C4291A6C9 2014-06-07 [expires: 2019-06-06]

Have you verified this user/key, and if so, what level do you want to sign at?
  0-3, Show again, Next, Help, or Quit? [0|1|2|3|s|n|h|q] (default: n) 3

Signing all UIDs on key 24735DD835689C84
DEBUG: Running: /usr/bin/gpg2 --keyid-format long --no-auto-check-trustdb -q --no-tty --batch --command-fd 0 --status-fd 1 --no-default-keyring --keyring /home/wget/.gnupg/pubring.kbx --no-options --with-colons --edit-key 24735DD835689C84
DEBUG: Got a line pub:-:4096:1:24735DD835689C84:1402173083:1559853083::-:::sc
DEBUG: Got a line fpr:::::::::47B22252BF6914DF964BB50C24735DD835689C84:
DEBUG: Got a line sub:-:4096:1:ECE04E5C4291A6C9:1402173083:1559853083:::::e
DEBUG: Got a line fpr:::::::::9B17D39506DA7F91BE5558EAECE04E5C4291A6C9:
DEBUG: Got a line uid:-::::::::Carl Olof Erlandsson <calle@thoughtbot.com>:::S9 S8 S7 S3 S2 S1 H8 H2 H9 H10 H11 Z2 Z3 Z1,mdc,no-ks-modify:1,p:
DEBUG: Got UID Carl Olof Erlandsson <calle@thoughtbot.com> with status -
DEBUG: got email calle@thoughtbot.com
DEBUG: 24735DD835689C84__calle_at_thoughtbot.com__0E7DE52C04D71683 isn't in []
DEBUG: Got a line uid:-::::::::Carl Olof Erlandsson <calle@calleerlandsson.com>:::S9 S8 S7 S3 S2 S1 H8 H2 H9 H10 H11 Z2 Z3 Z1,mdc,no-ks-modify:2,:
DEBUG: Got UID Carl Olof Erlandsson <calle@calleerlandsson.com> with status -
DEBUG: got email calle@calleerlandsson.com
DEBUG: 24735DD835689C84__calle_at_calleerlandsson.com__0E7DE52C04D71683 isn't in ['24735DD835689C84__calle_at_thoughtbot.com__0E7DE52C04D71683']
DEBUG: got to command prompt
DEBUG: quitting
DEBUG: waiting
  There are 2 UIDs on this key to sign
DEBUG: exporting 24735DD835689C84
DEBUG: Running: /usr/bin/gpg2 --keyid-format long --no-auto-check-trustdb -q --no-tty --batch --no-default-keyring --keyring /home/wget/.gnupg/pubring.kbx --armor --output /tmp/pius_tmp/24735DD835689C84.asc --export 24735DD835689C84 0E7DE52C04D71683
  UID 1 (calle@thoughtbot.com): DEBUG: Running: /usr/bin/gpg2 --keyid-format long --no-auto-check-trustdb -q --no-tty --batch --no-default-keyring --keyring /tmp/pius_tmp/pius_keyring.gpg --import-options import-minimal --import /tmp/pius_tmp/24735DD835689C84.asc
DEBUG: Running: /usr/bin/gpg2 --keyid-format long --no-auto-check-trustdb -q --no-tty --batch --command-fd 0 --status-fd 1 --no-default-keyring --keyring /tmp/pius_tmp/pius_keyring.gpg -u 0E7DE52C04D71683 --use-agent --default-cert-level 3 --no-ask-cert-level --edit-key 24735DD835689C84
DEBUG: Waiting for prompt
DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: Selecting UID 1
DEBUG: Waiting for ack
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Running sign subcommand
DEBUG: Waiting for line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: got line [GNUPG:] GET_LINE keyedit.prompt
DEBUG: Sending sign command
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Waiting for response
DEBUG: Got [GNUPG:] GET_BOOL sign_uid.okay

DEBUG: Confirming signing
DEBUG: Waiting for line [GNUPG:] GOT_IT
DEBUG: got line [GNUPG:] GOT_IT
DEBUG: Got [GNUPG:] GET_LINE keyedit.prompt

DEBUG: Saving key
signedDEBUG: exporting 24735DD835689C84
DEBUG: Running: /usr/bin/gpg2 --keyid-format long --no-auto-check-trustdb -q --no-tty --batch --no-default-keyring --keyring /tmp/pius_tmp/pius_keyring.gpg --armor --output /tmp/pius_out/24735DD835689C84__calle_at_thoughtbot.com__0E7DE52C04D71683.asc --export 24735DD835689C84
DEBUG: Running: /usr/bin/gpg2 --keyid-format long --no-auto-check-trustdb -q --no-tty --batch --command-fd 0 --status-fd 1 --no-default-keyring --keyring /tmp/pius_tmp/pius_keyring.gpg --always-trust --armor -r 24735DD835689C84 --output /tmp/pius_out/24735DD835689C84__calle_at_thoughtbot.com__0E7DE52C04D71683_ENCRYPTED.asc -e /tmp/pius_out/24735DD835689C84__calle_at_thoughtbot.com__0E7DE52C04D71683.asc
DEBUG: Waiting for response
DEBUG: Got [GNUPG:] PROGRESS need_entropy X 8 16
Traceback (most recent call last):
  File "/home/wget/IT/Dev/pius/pius", line 338, in <module>
    main()
  File "/home/wget/IT/Dev/pius/pius", line 322, in main
    if signer.sign_all_uids(key, retval):
  File "/home/wget/IT/Dev/pius/libpius/signer.py", line 767, in sign_all_uids
    self.encrypt_signed_uid(key, uid['file'])
  File "/home/wget/IT/Dev/pius/libpius/signer.py", line 436, in encrypt_signed_uid
    raise EncryptionUnknownError(line)
libpius.exceptions.EncryptionUnknownError: [GNUPG:] PROGRESS need_entropy X 8 16

```

Any idea about this new issue? This clearly indicates there is an entropy issue. But I have rng-tools enabled and this one is working flawlessly. Using the gpg command manually is working properly though. Why isn't this working with `pius`?

**Comment by jaymzh** [comment]
Heh we just fixed this in a different part of the code:
https://github.com/jaymzh/pius/blob/master/libpius/signer.py#L882

Busy week, but I'll try to get you a patch to try soon (basically around 434, add `elif PiusSigner.GPG_PROGRESS in line: continue` is the short-term fix, and abstracting that out better would be a better fix). The code-path you're using is less-utilized (you're not using the option to encrypt-email the signatures to people, but instead just encrypting the output files), which explains why you hit this but other's haven't.

**Comment by jaymzh** [comment]
2.2.2 is now out which fixes this.

**Comment by wget** [comment]
Great. Gonna check that out.
